# Generated by Django 3.0.7 on 2023-10-19 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default='00.50', max_digits=4)),
            ],
            options={
                'verbose_name': 'extra',
                'verbose_name_plural': 'extras',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('smPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('lgPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('numTop', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
                ('smPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('lgPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
                ('smPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('lgPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'topping',
                'verbose_name_plural': 'toppings',
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed', models.CharField(default='N', max_length=1)),
                ('extras', models.ManyToManyField(related_name='subs', to='orders.Extras')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subOrders', to='orders.Orders')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTyp', to='orders.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed', models.CharField(default='N', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladOrders', to='orders.Orders')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladTyp', to='orders.Salad')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed', models.CharField(default='N', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platterOrders', to='orders.Orders')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platterTyp', to='orders.Platter')),
            ],
        ),
        migrations.CreateModel(
            name='PizOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed', models.CharField(default='N', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizOrder', to='orders.Orders')),
                ('toppings', models.ManyToManyField(blank=True, related_name='customPiz', to='orders.Toppings')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizTyp', to='orders.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('completed', models.CharField(default='N', max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastaOrders', to='orders.Orders')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastaTyp', to='orders.Pasta')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='pastaItems',
            field=models.ManyToManyField(blank=True, related_name='pastaItems', to='orders.PastaOrder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pizItems',
            field=models.ManyToManyField(blank=True, related_name='pizItems', to='orders.PizOrder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='platItems',
            field=models.ManyToManyField(blank=True, related_name='platItems', to='orders.PlatterOrder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='saladItems',
            field=models.ManyToManyField(blank=True, related_name='saladItems', to='orders.SaladOrder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='subItems',
            field=models.ManyToManyField(blank=True, related_name='subItems', to='orders.SubOrder'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
