# Generated by Django 2.0.3 on 2020-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default='00.00', max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='pizItems',
            field=models.ManyToManyField(blank=True, related_name='pizItems', to='orders.PizOrder'),
        ),
        migrations.AddField(
            model_name='pizorder',
            name='orderID',
            field=models.ManyToManyField(related_name='pizOrders', to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='pizorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='customPiz', to='orders.Toppings'),
        ),
    ]
