# Generated by Django 2.0.3 on 2020-06-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200604_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizorder',
            old_name='orderID',
            new_name='order_id',
        ),
    ]
