# Generated by Django 3.0.7 on 2020-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200609_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_placed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
