# Generated by Django 3.0.7 on 2020-06-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200609_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extras',
            options={'verbose_name': 'extra', 'verbose_name_plural': 'extras'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name': 'topping', 'verbose_name_plural': 'toppings'},
        ),
    ]
