# Generated by Django 3.0.7 on 2020-06-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200610_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='pizorder',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pizOrder', to='orders.Orders'),
            preserve_default=False,
        ),
    ]
