# Generated by Django 3.0.7 on 2020-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200610_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastaorder',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pizorder',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='platterorder',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='saladorder',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='suborder',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
