# Generated by Django 3.0.7 on 2020-06-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200611_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastaorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pastaOrders', to='orders.Orders'),
        ),
        migrations.RemoveField(
            model_name='platterorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='platterorder',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='platterOrders', to='orders.Orders'),
        ),
        migrations.RemoveField(
            model_name='saladorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='saladorder',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='saladOrders', to='orders.Orders'),
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='suborder',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subOrders', to='orders.Orders'),
        ),
    ]
