# Generated by Django 3.0.7 on 2020-06-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200612_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastaorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastaOrders', to='orders.Orders'),
        ),
        migrations.AlterField(
            model_name='platterorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platterOrders', to='orders.Orders'),
        ),
        migrations.AlterField(
            model_name='saladorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladOrders', to='orders.Orders'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subOrders', to='orders.Orders'),
        ),
    ]
